---
- name: Ansible with Linux  
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Get the hostname
      debug:
        var: "This is the hostname { {ansible_hostname }}"

    - name: Reboot Server
      reboot:
      

    - name: Change the hostname
      hostname:
        name: EstoEsUnaPrueba

