---
- name: Ansible with Linux
  hosts: node1
  gather_facts: false
  become: true
  collections:
    - community.postgresql

  tasks:
    - name: Create a new database with name "acme" and specific encoding and locale # settings
      community.postgresql.postgresql_db:
        name: mydatabase
        encoding: UTF-8
        lc_collate: de_DE.UTF-8
        lc_ctype: de_DE.UTF-8
        template: template0
      become_user: postgres