---
- name: Ansible with Linux
  hosts: node1
  become: true
  tasks:
    - name: Create Database
      community.postgresql.postgresql_db:
        name: mydatabase
        state: present
      become_user: postgres