--- 
- name: Ansible with Linux  
  hosts: node1
  become: true
  tasks:  
  - name: Install Postgress    
    yum:
      name: '*'
      state: latest

  - name: Install Postgress
    yum:
      name: postgresql-server
      state: present