---
- name: Ansible with Linux
  hosts: node1
  gather_facts: false
  become: true
  collections:
    - community.postgresql
  tasks:
    - name: Grant Access to Database
      community.postgresql.postgresql_privs:
        database: mydatabase
        role: Boris
        privs: ALL
      become_user: postgres
