---
- name: Ansible with Linux
  hosts: node1
  gather_facts: false
  become: true
  collections:
    - community.postgresql
  tasks:
    - name: Create User
      community.postgresql.postgresql_user:
        name: Boris
        password: 123456
        superuser: yes
        role_attr_flags: LOGIN, CREATEDB