--- 
- name: Ansible with Linux  
  hosts: node1
  become: true
  tasks:

  - name: Habilitar y activar el servicio de PostgreSQL
    service:
      name: postgresql
      state: started
      enabled: true